model: gpt-4o-mini
messages:
  - role: system
    content: "Вы - полезный ассистент, который отвечает на вопросы пользователя четко и по существу."
  - role: user
    content: "{message}"
temperature: 0.7
max_tokens: 1000 